export const text = {
  ita: {
    title: "Daily Todo",
    close: "Chiudi",
    save: "Salva",
    today: "Oggi",
    enterText: "Cosa vuoi fare?",
    description: "Descrizione",
    descriptionPlaceholder: "Aggiungi una descrizione...",
    deadlineDate: "Scadenza",
    category: "Categoria",
    deadlineDateSelected: "Data selezionata",
    deadlineDateNotSelected: "Seleziona dal calendario",
    calendar: "Orario",
  },
  eng: {
    title: "Daily Todo",
    close: "Close",
    save: "Save",
    today: "Today",
    enterText: "What do you want to do?",
    description: "Description",
    descriptionPlaceholder: "Add a description...",
    deadlineDate: "Deadline",
    category: "Category",
    deadlineDateSelected: "",
    deadlineDateNotSelected: "",
    calendar: "Time",
  },
};
